In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset

In [2]:
data = pd.read_csv('bank_Churn_dataset.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Dropping the Unnecessary Columns

In [3]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1, inplace = True)
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [4]:
data.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [5]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Seeing for if  there is any unique dataset in Object dtatype to convert in to Numeric Form

In [6]:
for column in data:
    if data[column].dtypes == 'object':
        print(data[column].unique())

['France' 'Spain' 'Germany']
['Female' 'Male']


Replacing the categorical data to its numeric form

In [7]:
data['Gender'].replace({'Female':1, 'Male':0}, inplace = True)
data['Geography'].replace({'France':0, 'Spain':1, 'Germany':2}, inplace = True)

In [8]:
data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       1   42       2       0.00              1   
1          608          1       1   41       1   83807.86              1   
2          502          0       1   42       8  159660.80              3   
3          699          0       1   39       1       0.00              2   
4          850          1       1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
for column in data:
    if data[column].dtypes == 'object':
        print(data[column].unique())
#there are no unique elements

Scaling the data for the columns ['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary']

In [10]:
data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       1   42       2       0.00              1   
1          608          1       1   41       1   83807.86              1   
2          502          0       1   42       8  159660.80              3   
3          699          0       1   39       1       0.00              2   
4          850          1       1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [11]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaling_column = ['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary']
data[scaling_column] = scaler.fit_transform(data[scaling_column])

In [12]:
data.head()

CreditScore  Geography  Gender       Age  Tenure   Balance  NumOfProducts  \
0        0.538          0       1  0.324324     0.2  0.000000              1   
1        0.516          1       1  0.310811     0.1  0.334031              1   
2        0.304          0       1  0.324324     0.8  0.636357              3   
3        0.698          0       1  0.283784     0.1  0.000000              2   
4        1.000          1       1  0.337838     0.2  0.500246              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1         0.506735       1  
1          0               1         0.562709       0  
2          1               0         0.569654       1  
3          0               0         0.469120       0  
4          1               1         0.395400       0

Allocating the X dataset and y dataset

In [13]:
X = data.drop('Exited', axis = 1)
y = data['Exited']

Splitting the dataset with 80% training model and 20 % testing Model

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 43)

In [15]:
X_train.shape, X_test.shape

((8000, 10), (2000, 10))

In [16]:
import tensorflow
from tensorflow import keras

Creating the Artificial Neural Network Model using mini btch gradient Descent

 I have taken mini batch size as 10 because to get high accuracy evenhough it takes time

In [17]:
model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size = 10)

Epoch 1/100
800/800 [==============================] - 10s 2ms/step - loss: 0.4957 - accuracy: 0.8022 0s - loss: 0.4961 - accuracy: 0.80
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4635 - accuracy: 0.7975
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4442 - accuracy: 0.8087
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4318 - accuracy: 0.8122
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4229 - accuracy: 0.8158
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4302 - accuracy: 0.8105
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4165 - accuracy: 0.8248
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4141 - accuracy: 0.8246
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4070 - accuracy: 0.8287
Epoch 10/100
800/800 [==============================] -

In [18]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 1s 2ms/step - loss: 0.3541 - accuracy: 0.8510


[0.3541034162044525, 0.8510000109672546]

In [19]:
y_predicted = model.predict(X_test)
y_predicted[:5]

array([[0.21454719],
       [0.3026249 ],
       [0.29456455],
       [0.21224856],
       [0.45287624]], dtype=float32)

In [20]:
y_test[:5]

9415    0
6377    1
8019    0
7754    1
4961    0
Name: Exited, dtype: int64

In [21]:
y_predicted = np.asanyarray(y_predicted)
y_predicted

array([[0.21454719],
       [0.3026249 ],
       [0.29456455],
       ...,
       [0.00889936],
       [0.5594953 ],
       [0.17289022]], dtype=float32)

In [22]:
len(y_predicted)

2000

In [23]:
y_predicted[1]

array([0.3026249], dtype=float32)

In [24]:
y_predict = []
for i in range(len(y_predicted)):
    if y_predicted[i] > 0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)


In [25]:
y_predict[:5]

[0, 0, 0, 0, 0]

Confusion matrix

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[1501,   87],
       [ 211,  201]], dtype=int64)

Classification Report

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1588
           1       0.70      0.49      0.57       412

    accuracy                           0.85      2000
   macro avg       0.79      0.72      0.74      2000
weighted avg       0.84      0.85      0.84      2000



# Handling imbalanced data using Undersampling

In [28]:
data['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [29]:
class_0_counts, class_1_counts = data['Exited'].value_counts()
print(class_0_counts, class_1_counts)

7963 2037


In [30]:
class_0_data = data[data['Exited'] == 0] #class 0 samples
class_1_data = data[data['Exited'] == 1] #class 1 samples

In [31]:
class_0_data.shape, class_1_data.shape

((7963, 11), (2037, 11))

Undersampling the 0 class dataset

In [32]:
under_sampled_class_0 = class_0_data.sample(class_1_counts)
under_sampled_class_0.shape

(2037, 11)

In [33]:
print(under_sampled_class_0.shape, class_1_data.shape)
# both the dataset has same shape

(2037, 11) (2037, 11)


Concating both the datasets

In [34]:
under_sample_dataset = pd.concat([under_sampled_class_0, class_1_data], axis = 0)
under_sample_dataset.shape

(4074, 11)

In [35]:
X = under_sample_dataset.drop('Exited', axis = 1)
y = under_sample_dataset['Exited']

Splitting and training the model using ANN

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 43)

model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size = 10)

Epoch 1/100
326/326 [==============================] - 4s 2ms/step - loss: 0.6825 - accuracy: 0.5514
Epoch 2/100
326/326 [==============================] - 1s 2ms/step - loss: 0.6417 - accuracy: 0.6423
Epoch 3/100
326/326 [==============================] - 1s 2ms/step - loss: 0.6302 - accuracy: 0.6410
Epoch 4/100
326/326 [==============================] - 1s 2ms/step - loss: 0.6060 - accuracy: 0.6813
Epoch 5/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5920 - accuracy: 0.6881
Epoch 6/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5737 - accuracy: 0.7071
Epoch 7/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5686 - accuracy: 0.7046
Epoch 8/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5540 - accuracy: 0.7246
Epoch 9/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7109
Epoch 10/100
326/326 [==============================] - 1s 2ms/step - loss: 0.5360 - accura

Evaluating the Model

In [37]:
model.evaluate(X_test, y_test)

26/26 [==============================] - 0s 2ms/step - loss: 0.4646 - accuracy: 0.7706


[0.46459099650382996, 0.7705521583557129]

Predicting the model and converting the output as 1 and 0 using 0.5 as threshold

In [38]:
y_predicted = model.predict(X_test)
y_predicted = np.asanyarray(y_predicted)
y_predict = []
for i in range(len(y_predicted)):
    if y_predicted[i] > 0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)

Confusion Matrix

In [39]:
confusion_matrix(y_test, y_predict)

array([[311,  92],
       [ 95, 317]], dtype=int64)

Classification report

In [40]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77       403
           1       0.78      0.77      0.77       412

    accuracy                           0.77       815
   macro avg       0.77      0.77      0.77       815
weighted avg       0.77      0.77      0.77       815



Hence the f1-score of  the classes 0 - (0.92) and 1 - (0.59) has changed to classes 0 - (0.77) and 1 - (0.75)..  
So, overall f1 Score is better than the previous ANN model wihout handling imbalanced dataset

#  Handling imbalanced data using Oversampling : Duplicate Copy

In [41]:
class_0_counts, class_1_counts

(7963, 2037)

In [42]:
class_0_data.shape, class_1_data.shape

((7963, 11), (2037, 11))

Making the dataset equal in number randomly copying any dataset in class1

In [43]:
under_sampled_class_1 = class_1_data.sample(class_0_counts, replace=True)
class_0_data.shape, under_sampled_class_1.shape

((7963, 11), (7963, 11))

Concatinating both the dataset

In [44]:
over_sample_dataset = pd.concat([class_0_data, under_sampled_class_1], axis = 0)
over_sample_dataset.shape

(15926, 11)

In [45]:
X = over_sample_dataset.drop('Exited', axis = 1)
y = over_sample_dataset['Exited']

Splitting the in train and test and executing the ANN Model

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 43)

model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size = 10)

Epoch 1/100
1274/1274 [==============================] - 3s 2ms/step - loss: 0.6602 - accuracy: 0.6070
Epoch 2/100
1274/1274 [==============================] - 3s 2ms/step - loss: 0.5858 - accuracy: 0.7129
Epoch 3/100
1274/1274 [==============================] - 3s 2ms/step - loss: 0.5433 - accuracy: 0.7422
Epoch 4/100
1274/1274 [==============================] - 3s 3ms/step - loss: 0.5153 - accuracy: 0.7535
Epoch 5/100
1274/1274 [==============================] - 4s 3ms/step - loss: 0.4890 - accuracy: 0.7633
Epoch 6/100
1274/1274 [==============================] - 3s 2ms/step - loss: 0.4845 - accuracy: 0.7659
Epoch 7/100
1274/1274 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7698
Epoch 8/100
1274/1274 [==============================] - 2s 1ms/step - loss: 0.4771 - accuracy: 0.7649
Epoch 9/100
1274/1274 [==============================] - 2s 2ms/step - loss: 0.4756 - accuracy: 0.7653
Epoch 10/100
1274/1274 [==============================] - 3s 2ms/step - l

Evaluating the Model

In [47]:
model.evaluate(X_test, y_test)

100/100 [==============================] - 0s 1ms/step - loss: 0.4276 - accuracy: 0.7897


[0.4276498556137085, 0.7897049784660339]

Predicting the model and converting the output as 1 and 0 using 0.5 as threshold

In [48]:
y_predicted = model.predict(X_test)
y_predicted = np.asanyarray(y_predicted)
y_predict = []
for i in range(len(y_predicted)):
    if y_predicted[i] > 0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)

Confusion Matrix

In [49]:
confusion_matrix(y_test, y_predict)

array([[1317,  267],
       [ 403, 1199]], dtype=int64)

Classification Report

In [50]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80      1584
           1       0.82      0.75      0.78      1602

    accuracy                           0.79      3186
   macro avg       0.79      0.79      0.79      3186
weighted avg       0.79      0.79      0.79      3186



Hence the f1-score of  the classes 0 - (0.92) and 1 - (0.59) has changed to classes 0 - (0.80) and 1 - (0.79)..  
So, overall f1 Score is better than the previous ANN model wihout handling imbalanced dataset

#  Handling imbalanced data using Oversampling : SMOTE

In [51]:
class_0_counts, class_1_counts

(7963, 2037)

Splitting X and y data

In [52]:
X = data.drop('Exited', axis = 1)
y = data['Exited']

SMOTE uses KNN to make duplicate dataset which is better than randomly copying the data 

In [ ]:
!pip install imbalanced-learn

In [53]:
from imblearn.over_sampling import SMOTE

ModuleNotFoundError: No module named 'imblearn'

In [ ]:
smote = SMOTE(sampling_strategy='minority')
X_data, y_data = smote.fit_sample(X, y)

In [ ]:
y_data.value_counts()
# both the classes data is same

Splitting the train and test sample and executing the ANN model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size = 0.2, random_state = 43)

model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size = 10)

Evaluating the Model

In [ ]:
model.evaluate(X_test, y_test)

Predicting the model and converting the output as 1 and 0 using 0.5 as threshold

In [ ]:
y_predicted = model.predict(X_test)
y_predicted = np.asanyarray(y_predicted)
y_predict = []
for i in range(len(y_predicted)):
    if y_predicted[i] > 0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)

Confusion Matrix

In [ ]:
confusion_matrix(y_test, y_predict)

Classification Report

In [ ]:
print(classification_report(y_test, y_predict))

Hence the f1-score of  the classes 0 - (0.92) and 1 - (0.59) has changed to classes 0 - (0.80) and 1 - (0.79)..  
So, overall f1 Score is better than the previous ANN model wihout handling imbalanced dataset

#  Handling imbalanced data using Ensemble

In [ ]:
X = data.drop('Exited', axis = 1)
y = data['Exited']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 43)

In [ ]:
data['Exited'].value_counts()

In [ ]:
class_0_data.shape, class_1_data.shape

In [ ]:
print("Actual count", (7963/2037))
print("Round of count", round(7963/2037))

The data is approximately in ratio of 4

Now taking the dataset of class 0 and class 1 and making them equal in examples by dividing the training set in same  
length as test data and creaing different models

Creating the Funtion to make different classes of dataset 

In [ ]:
def creating_class_of_same_training_and_testing_dataset(start_index, end_index):
    dataset_ = pd.concat([class_0_data[start_index:end_index], class_1_data], axis = 0)
    X_train = dataset_.drop('Exited', axis = 1)
    y_train = dataset_['Exited']
    return X_train, y_train
    

Creating 4 different datset classes of same number of both same training and testing dataset 

In [ ]:
X_train1, y_train1 = creating_class_of_same_training_and_testing_dataset(0,2037)
X_train2, y_train2 = creating_class_of_same_training_and_testing_dataset(2037,4074)
X_train3, y_train3 = creating_class_of_same_training_and_testing_dataset(4074,6111)
X_train4, y_train4 = creating_class_of_same_training_and_testing_dataset(6111,7964)

In [ ]:
X_train1.shape, X_test.shape

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train1, y_train1, epochs=100, batch_size = 10)

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_predicted_1 = model.predict(X_test)
y_predicted_1 = np.asanyarray(y_predicted_1)
y_predict_1 = []
for i in range(len(y_predicted_1)):
    if y_predicted_1[i] > 0.5:
        y_predict_1.append(1)
    else:
        y_predict_1.append(0)

In [ ]:
print(classification_report(y_test, y_predict_1))

for 2nd class dataset

In [ ]:
X_train2.shape, X_test.shape

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train2, y_train2, epochs=100, batch_size = 10)

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_predicted_2 = model.predict(X_test)
y_predicted_2 = np.asanyarray(y_predicted_2)
y_predict_2 = []
for i in range(len(y_predicted_2)):
    if y_predicted_2[i] > 0.5:
        y_predict_2.append(1)
    else:
        y_predict_2.append(0)

In [ ]:
print(classification_report(y_test, y_predict_2))

for 3rd class dataset

In [ ]:
X_train3.shape, X_test.shape

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train3, y_train3, epochs=100, batch_size = 10)

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_predicted_3 = model.predict(X_test)
y_predicted_3 = np.asanyarray(y_predicted_3)
y_predict_3 = []
for i in range(len(y_predicted_3)):
    if y_predicted_3[i] > 0.5:
        y_predict_3.append(1)
    else:
        y_predict_3.append(0)

In [ ]:
print(classification_report(y_test, y_predict_3))

for 4th class dataset

In [ ]:
X_train4.shape, X_test.shape

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(15, input_shape = (10, ), activation = 'relu'),
    keras.layers.Dense(10, activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

model.fit(X_train4, y_train4, epochs=100, batch_size = 10)

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_predicted_4 = model.predict(X_test)
y_predicted_4 = np.asanyarray(y_predicted_4)
y_predict_4 = []
for i in range(len(y_predicted_4)):
    if y_predicted_4[i] > 0.5:
        y_predict_4.append(1)
    else:
        y_predict_4.append(0)

In [ ]:
print(classification_report(y_test, y_predict_4))

In [ ]:
len(y_predict_1),len(y_predict_2), len(y_predict_3),len(y_predict_4)

The majority vote out of all the y_predicted values

As i have even classes, so i am taking the copy of maximum precision and recall class(y_predict_3) and when he count 
is 2 then i am assigning the value as of y_predict_3

In [ ]:
y_predict_result = y_predict_3.copy()
for i in range(len(y_predict_4)):
    value = y_predict_1[i] + y_predict_2[i]+ y_predict_3[i] + y_predict_4[i]
    if value <= 1:
        y_predict_result[i] = 0
    if value == 2 :
        y_predict_result[i] = y_predict_3[i]
    if value > 2 :
        y_predict_result[i] = 1
    

Final confusion matrix of ensemble method

In [ ]:
confusion_matrix(y_test, y_predict_result)

Final classification report of ensemble method

In [ ]:
print(classification_report(y_test, y_predict_result))

Hence the f1-score of  the classes 0 - (0.92) and 1 - (0.59) has changed to classes 0 - (0.87) and 1 - (0.60)..  
So, overall f1 Score is better than the previous ANN model wihout handling imbalanced dataset